### ISSUE TITLE
Add support for completion requests from empty character

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#112]
Given:
```xml
<foo>
    <bar>
     // press ctrl-space here
</foo>
```

There's no completion until I press `<`. While I understand autocompletion is triggered on `<`, explicit completion requests (`ctrl+space`), should also return results from anywhere in the document. In this case, it should return `</bar>`.

In Eclipse, when explicitely requesting completion from an empty space, you get :
1 - proposition to close the last opened tag
2 - list of all possible tags (i.e existing siblings)

![xml-complete](https://user-images.githubusercontent.com/148698/45300226-c45bfb00-b4db-11e8-8f12-d19dab2da315.gif)

1/ is really important. 2/ we can probably live without for a bit.

**Comment by angelozerr** [comment]
This issue is for several features. Now completion with ctrl+space provides elements:

![image](https://user-images.githubusercontent.com/1932211/45585819-65d3ba00-b8eb-11e8-92b4-d09a7f594b9f.png)

1) is working only when you are after the start of element

![image](https://user-images.githubusercontent.com/1932211/45585828-8c91f080-b8eb-11e8-83cd-2fc6b08b8313.png)

2) starts working

![image](https://user-images.githubusercontent.com/1932211/45585840-cc58d800-b8eb-11e8-97ee-72cd29483b89.png)

**Comment by angelozerr** [comment]
> So here's a strange behaviour. 

I will fix it.

**Comment by angelozerr** [comment]
@fbricon your problem should be fixed now. The last thing I must support is the close tag.

**Comment by angelozerr** [comment]
@fbricon I have improved a lot the close tag (works with empty character, indent apply of completion, provide several close tag to close. See the following demo:

![closetag](https://user-images.githubusercontent.com/1932211/46638720-8dbce300-cb62-11e8-9e89-a04de7368f55.gif)

Please closet this issue of it's OK for you.

**Comment by fbricon** [comment]
Very nice @angelozerr! Me likey

**Comment by angelozerr** [comment]
Glad it pleases you @fbricon !
