### ISSUE TITLE
Add pom.xml extension

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#166]
It should be cool to create a new maven project extension to:

 * have some completion like:

![image](https://user-images.githubusercontent.com/1932211/47214170-699ca580-d39d-11e8-89c5-e14aed3194e0.png)

 * have validation for the directory declaration
 * have completion for deprendency
 * have codelens for dependency like https://github.com/angelozerr/lsp4xml/issues/55

and other ideas...

It should be cool to use https://github.com/angelozerr/lsp4xml/issues/168

**Comment by fbricon** [comment]
Dependency completion might belong to a jdt.ls extension instead, as you need to load the Maven model to know about dependencies in dependencyManagement, from the pom hierarchy. But I guess this is debatable

**Comment by Eskibear** [comment]
Is there any update on this? When and where (jdt.ls or lsp4xml, or anywhere else) is it supposed to be implemented?  I mean, it's a good feature for Maven users and I'm just longing for it.

**Comment by mickaelistria** [comment]
> Dependency completion might belong to a jdt.ls extension instead, as you need to load the Maven model to know about dependencies in dependencyManagement, from the pom hierarchy. But I guess this is debatable

If we can make the Maven support separated from JDT-LS, that would be much better IMO. One can totally do some Maven stuff without working on Java project (I used to do this kind of stuff of simply managing some parent poms here and there), and I guess a good support only requires to use Maven APIs and nothing from JDT.
For sure, there would be some risk of duplication of Maven models between the various language servers, but it's not yet a critical enough issue to make it a blocker.
So either a dedicated Maven LS or an dedicated Maven extension to XML-LS seem a better approach as it enables more reusability (some mid-term goal would be to have for instance Eclipse m2e using such LSP-based approach for pom edition rather than WTP.SSE editors, so we could collectively improve support in all IDEs at once).

**Comment by angelozerr** [comment]
I can initialize the extension if you wish an add definition to open parent maven pom.xml. But it's not in our priority for the moment. Any help are welcome! If some guys want to work on this task, I could assist him.

**Comment by mickaelistria** [comment]
We have other things going on at the moment, but getting rid of WTP editors in favor of Generic Editor and Language Servers is progressively getting higher and higher in our priorities, so we'll keep in touch ;)

**Comment by angelozerr** [comment]
For maven support with LSP4XML, please create issues at https://github.com/angelozerr/lsp4xml-extensions-maven
