### ISSUE TITLE
xsd files can only be edited if useCache is enabled

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#186]
Given:
```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.w3.org/2001/XMLSchema
                               http://www.w3.org/2001/XMLSchema.xsd">

</xs:schema>
```

when useCache is disabled, the document fails to validate (even if stuff was cached in .lsp4xml before). I get:
- error: cvc-elt.1.a: Cannot find the declaration of element 'xs:schema'.
- warning: schema_reference.4: Failed to read schema document 'http://www.w3.org/2001/XMLSchema.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.

Looks like, by default, if clients don't send the useCache:true, the preference is unmarshalled as false, overriding the server's default value, thus breaking xsd editing.

**Comment by fbricon** [comment]
No matter what if useCache=false, it should not produce any errors.

**Comment by angelozerr** [comment]
Thanks for the feedback, I will try that and Im' working on xsd extension in https://github.com/angelozerr/lsp4xml/issues/178

**Comment by angelozerr** [comment]
@fbricon I think https://github.com/angelozerr/lsp4xml/commit/896776438519fcdf91a51c600cebc0f582799e2d should fix a lot of problem that you have with file assocoiation, this issue, the https://github.com/angelozerr/lsp4xml/issues/178 but I'm writing a lot of test to check that

**Comment by angelozerr** [comment]
@fbricon is https://github.com/angelozerr/lsp4xml/commit/896776438519fcdf91a51c600cebc0f582799e2d fix this problem (after waiting for one minute)?

**Comment by fbricon** [comment]
It works now even if useCache=false. Although it actually use a local cache but my understanding is it just unpacks embedded schemas.

**Comment by fbricon** [comment]
If you have tests for it, you can close it now

**Comment by angelozerr** [comment]
> It works now even if useCache=false. Although it actually use a local cache but my understanding is it just unpacks embedded schemas.

Yes it's exaclty that, XML Schemas, dtd from classpath https://github.com/angelozerr/lsp4xml/tree/master/org.eclipse.lsp4xml/src/main/resources/schemas are deployed in the cache folder, exactly the same folder when cache is enabled.

Today test disable cache, because using cache means asynch validation, etc

Test for XSD are:

 * for validation, see https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/java/org/eclipse/lsp4xml/extensions/xsd/XSDValidationExtensionsTest.java

 * for completion, see https://github.com/angelozerr/lsp4xml/blob/master/org.eclipse.lsp4xml/src/test/java/org/eclipse/lsp4xml/extensions/xsd/XSDCompletionExtensionsTest.java
