### ISSUE TITLE
Interaction with Eclipse WTP.XML

### ISSUE THREAD

**Issue by mickaelistria** [angelozerr/lsp4xml#2]
I see as part of this project tries to implement it's own parser. I think it's a really hard task from short to long term!
Have you consider re-using Eclipse WTP parser or some other parser (like the one used by IntelliJ) to build the server upon?

**Comment by angelozerr** [comment]
> I see as part of this project tries to implement it's own parser. I think it's a really hard task from short to long term!

Indeed, it's the hard part of language server. But I'm confident because this parser is a port of HTML Language Service parser written in TypeScript by Microsoft.

> Have you consider re-using Eclipse WTP parser or some other parser (like the one used by IntelliJ) to build the server upon?

I have tried but it's so very hard, because the parser is linked to SSE structure which requires several dependencies. I have not found a very good tolerant XML parser with location which is light and works good.

**Comment by mickaelistria** [comment]
> I have tried but it's so very hard, because the parser is linked to SSE structure which requires several dependencies.

The SSE structure

**Comment by mickaelistria** [comment]
> I have tried but it's so very hard, because the parser is linked to SSE structure which requires several dependencies.

Ok. I guess it is

**Comment by angelozerr** [comment]
I close this issue since we have done a lot of work with @NikolasKomonen with the parser and it starts working well.
