### ISSUE TITLE
Provide file/folder completion for certain xml attributes

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#345]
When an attribute is named:
- src
- path
- directory
- file
(list could be defined in some preferences), then lsp4xml should propose file completion.
Also, that could be triggered by any attribute value starting with the file:// scheme.

eg (html support in vscode):
![Apr-04-2019 16-05-12](https://user-images.githubusercontent.com/148698/55584952-8599c680-56f3-11e9-9809-71ca15136b0c.gif)

**Comment by bmix** [comment]
What about adding support for the `xml:base` attribute, valid for the current XML context, as root for the completion? 

`xml:base` allows for links to be relative, which then get resolved by an iri-handler, by concatenating the path from the currently valid `xml:base` attribute with the relative reference.

Example (let the file in edition be `/projects/clientA/documents/example.xml`):
```xml
<document xml:base="http://example.com/documents/">
  <title>Some Title</title>
  <icon href="icon.png"/> <!-- means: 'http://example.com/documents/icon.png' -->
  <text>Lorem Ipsum and so on...</text>
  <figures xml:base="http://example.com/documents/figures/">
    <fig href="-> This triggers listing all images under '/documents/figures/'
  </figures>
</document>
```

Of course, this would make only sense for environments, that implement some logic to map any non `file://` IRI to the local filesystem:

    settings.remote.path.url = "http://example.com"
    settings.local.path.url = "/projects/clientA/"

Such settings would typically be part of the project's preferences.

Resolution of the currently valid such attribute would, I believe, require the same code, as may be existing for namespace resolution, `xml:lang` and `xml:space`, because the principles are the same.
