### ISSUE TITLE
Completion provides invalid suggestions for xsd:sequence

### ISSUE THREAD

**Issue by cassianstraessle** [angelozerr/lsp4xml#347]
```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xs:element name="data">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="e1"/>
                <xs:element name="e2"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
```
Given the schema above the code completion shows the following behavior:

- for the very fist element in `<data>` the code completion suggests both elements `<e1>` and `<e2>`. But only `<e1>` is a valid choice.
- for the second element in <data> the code completion suggests both elements` <e1>` and `<e2>`. But only `<e2>` is a valid choice.

The schema validation correctly points out the invalid elements. But code completion should not suggest invalid elements in the first place.

I observed this behavior with redhat.vscode-xml v0.5.0

**Comment by kduvekot** [comment]
as an addition ... it looks like the suggestions are always in alphabetical order, and ideally you want to get the suggestions in the sequence order, and restricted to what is possible at the location where the suggestion is make. (so limited to the elements that would "fit" there based on previous and next elements in the document)

I am working with UBL XSDs where sequence is important:
http://docs.oasis-open.org/ubl/os-UBL-2.2/xsd/maindoc/

Also when you have a sequence and there are mandatory elements (<xsd:element minOccurs="1" maxOccurs="1"> it would be good to insert those when the parent element of that sequence is started. You already know that the XML wil not be valid without those mandatory elements anyway.

and while you are at it ... then also insert the possible mandatory attributes of those elements :-)

I would not go as far as inserting the mandatory elements of complexType elements in the original sequence.. because they might be recursive .. so that would dig you down into a very deep rabbit hole.

**Comment by NikolasKomonen** [comment]
Hi, I'm working on this issue right now trying to make sure it covers all cases. I will try to have a pr soon, which I hope people can test out to see if anything is missing.

For XSD based completion the server should eventually cover:
 * Consider the model group (all, choice, sequence)
   * Recognize already existing elements
   * Provide the next required element(s) in a sequence
 * Consider the max/min occurrences 
 * Consider 'substitutionGroup' (already did that, but considers the model group)
 * Handle elements that have the 'absolute' attribute set.
 * <xs:any> elements that can link to other XSD's
 * Auto insert top level required elements (may be in different pr)

Let me know if you see any possible cases that are missing.
   

> then also insert the possible mandatory attributes of those elements

thanks @kduvekot for the idea, I'll make sure we implement this.

**Comment by angelozerr** [comment]
@cassianstraessle  @kduvekot @NikolasKomonen I'm working again on this (hard) issue. I hope it will be avaialble for 0.8.0 millestone.

@NikolasKomonen I think we should use XSCMValidator  from xerces that it is used in XMLSchemaValidator. I'm working on this idea.
