### ISSUE TITLE
Selection formatting ignores attribute indentation preference

### ISSUE THREAD

**Issue by fbricon** [angelozerr/lsp4xml#429]
With `"xml.format.splitAttributes": true`, selection formatting still puts the 1st attribute on the same line as the opening tag:

![Jun-11-2019 14-32-00](https://user-images.githubusercontent.com/148698/59297248-ce22b280-8c55-11e9-9f0e-ed9c0323a179.gif)

**Comment by xorye** [comment]
@fbricon What do you think about this interaction?

![attribute formatting example](https://raw.githubusercontent.com/xorye/gifs/master/%23429/429g1.gif)

I think it might be better so that only the second attribute becomes formatted since that is what is being selected, however, it will complicate things just a bit more.

**Comment by fbricon** [comment]
I can live with that
