### ISSUE TITLE
Add JUnit for tolerant XMLParser

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/lsp4xml#7]
Add JUnit for tolerant XMLParser

@NikolasKomonen please follow this issue to track JUnit that I will do. Once I will push my work, please give me feedback to know if you will like tests and do the same thing for CDATA https://github.com/angelozerr/xml-languageserver/issues/5

**Comment by angelozerr** [comment]
@NikolasKomonen @fbricon I have created test for XML Parser at https://github.com/angelozerr/xml-languageserver/blob/master/org.eclipse.xml.languageserver/src/test/java/org/eclipse/xml/languageserver/internal/parser/XMLParserTest.java

My goal is to have test which are easy to read, that's why I'm using String. I have adapted test of HTML language service parser https://github.com/Microsoft/vscode-html-languageservice/blob/master/src/test/parser.test.ts for XML

Hope you will like it, otherwise don't hesitate to tell me what you don't like.

**Comment by NikolasKomonen** [comment]
@angelozerr I like the structure but I think the format could be changed to make it easier to find issues when they appear. Right now when errors are reported they are not always easily located especially if a larger XML document with a  children are tested or there are multiple errors. 

What I think we could do is instead compare individual values through inside a function where we pass (Node toTest, tagName, start, end, ...) and then also do this for children since it wont force the entire tree to be placed into one block of text.

I'll work on an implementation and we can decide from there.

**Comment by angelozerr** [comment]
Tests are covered by https://github.com/angelozerr/lsp4xml/pull/17

Tanks @NikolasKomonen !
